root = "."

tmp_dir = "tmp"

[build]
pre_cmd = ["task generate"]

# cmd = "task $BIN:dev:build" - to be set dynamically when running air cmd

# Binary file yields from `cmd`.
# bin = "tmp/$BIN{.exe(windows)}" - to be set dynamically when running air cmd

# Watch these filename extensions.
include_ext = ["go", "templ", "proto", "sql"]

# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "node_modules"]

# Watch these directories if you specified.
include_dir = []

# Watch these files.
include_file = ["go.mod", "go.sum", "sqlc.yaml", "buf.yaml", "buf.gen.yaml"]

# Exclude files.
exclude_file = []

# Exclude specific regular expressions.
exclude_regex = ["_test\\.go"]

# Exclude unchanged files.
exclude_unchanged = true

# Follow symlink for directories
follow_symlink = true

# This log file is placed in your tmp_dir.
log = "air.log"

# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 500 # ms

# Stop running old binary when build errors occur.
stop_on_error = true

# Send Interrupt signal before killing process (windows does not support this feature)
send_interrupt = true

# Delay after sending Interrupt signal
kill_delay = 2000

[log]
# Show log time
time = false
# Only show main log (silences watcher, build, runner)
main_only = false
# silence all logs produced by air 
silent = true

[misc]
# Delete tmp directory on exit
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
