scrape_configs:
    - job_name: guardian
      metrics_path: /metrics
      scheme: http
      static_configs:
          - targets: ["localhost:9002"]

global:
    scrape_interval: "10s"
    scrape_timeout: "2s"
